base_url = "https://yshngg.dev"
title = "Yusheng - An Open Source Developer"
description = ""
output_dir = "public"
default_language = "en"
compile_sass = false
build_search_index = false

taxonomies = [
    { name = "category", feed = true },
    { name = "tags", feed = true },
]

[languages.zh]
taxonomies = [
    { name = "category", feed = true },
    { name = "tags", feed = true },
]

[slugify]
anchors = "safe"

[markdown]
insert_anchor_links = "heading"

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
